name: CI Pipeline

on:
  push:
    branches: [master] # Run when changes are pushed to the 'master' branch
  pull_request:
    branches: [master] # Also run when pull requests are made to the 'master' branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
